name: Build & Push dask-energyplus (multi-arch)

on:
  # Manual run with inputs
  workflow_dispatch:
    inputs:
      eplus_tag:
        description: "EnergyPlus release tag to install (e.g., v25.1.0)"
        required: false
        default: "v25.1.0"
      image_tag:
        description: "Primary image tag (e.g., 25.1)"
        required: false
        default: "25.1"
      push_latest:
        description: "Also push :latest?"
        type: boolean
        required: false
        default: false
  # Auto-run on changes to the Dockerfile (optional)
  push:
    branches: [ main ]
    paths:
      - "Dockerfile"

permissions:
  contents: read
  packages: write

concurrency:
  group: build-dask-energyplus-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build-push:
    runs-on: ubuntu-latest
    env:
      REGISTRY_IMAGE: samuelduchesne/dask-energyplus
      EPLUS_TAG: ${{ inputs.eplus_tag || 'v25.1.0' }}
      IMAGE_TAG: ${{ inputs.image_tag || '25.1' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU (for multi-arch emulation)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Optional: derive full tag list (25.1, v25.1.0, and optionally latest)
      - name: Compute tags
        id: tags
        run: |
          TAGS="${REGISTRY_IMAGE}:${IMAGE_TAG},${REGISTRY_IMAGE}:${EPLUS_TAG}"
          if [ "${{ inputs.push_latest }}" = "true" ] || [ "${{ github.ref }}" = "refs/heads/main" ]; then
            TAGS="${TAGS},${REGISTRY_IMAGE}:latest"
          fi
          echo "tags=${TAGS}" >> "$GITHUB_OUTPUT"

      - name: Build & Push (linux/amd64, linux/arm64)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.tags.outputs.tags }}
          build-args: |
            EPLUS_TAG=${{ env.EPLUS_TAG }}
            # Forward a token to increase GitHub API rate limits for curl calls in the Dockerfile.
            # Your Dockerfile uses it conditionally and does not echo the value.
            GITHUB_TOKEN=${{ github.token }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false  # set true if you want SLSA/provenance metadata
